/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginform',

    requires: [
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.field.Password',
        'Ext.Button',
        'Ext.Toolbar'
    ],

    config: {
        scrollable: false,
        items: [
            {
                xtype: 'container',
                height: 60,
                margin: '5% 5% 1% 5%',
                scrollable: false,
                items: [
                    {
                        xtype: 'image',
                        centered: true,
                        docked: 'bottom',
                        height: 60,
                        left: '',
                        margin: '',
                        top: '',
                        width: 100,
                        src: 'resources/images/logo.jpg'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                centered: false,
                margin: '',
                title: '',
                layout: {
                    type: 'vbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'textfield',
                        centered: false,
                        itemId: 'username',
                        width: '80%',
                        label: '',
                        name: 'j_username',
                        maxLength: 25,
                        placeHolder: '请输入您的用户名'
                    },
                    {
                        xtype: 'passwordfield',
                        centered: false,
                        itemId: 'password',
                        width: '80%',
                        name: 'j_password',
                        maxLength: 25,
                        placeHolder: '请输入您的密码'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'loginButton',
                margin: 20,
                padding: 8,
                ui: 'confirm-round',
                text: '登录'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        docked: 'left',
                        itemId: 'registerBtn',
                        ui: 'action',
                        text: '注册账号'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        ui: 'action',
                        text: '忘记密码'
                    }
                ]
            }
        ]
    }

});