/*
 * File: app/view/PullRefreshPlugin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.PullRefreshPlugin', {
    extend: 'Ext.plugin.PullRefresh',
    alias: 'plugin.refreshFn',

    config: {
        lastUpdatedDateFormat: 'Y-m-d H:i',
        lastUpdatedText: '上次刷新时间',
        loadedText: '加载完成',
        loadingText: '正在加载',
        pullText: '下拉可以更新',
        releaseText: '松开开始更新',
        type: 'pullrefresh'
    },

    initialize: function() {
        this.callParent();
    }

});