/*
 * File: app/view/RegisterForm.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.RegisterForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.registerform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Password',
        'Ext.field.Select',
        'Ext.field.Spinner',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.Label'
    ],

    config: {
        scrollable: 'vertical',
        items: [
            {
                xtype: 'fieldset',
                height: '50%',
                items: [
                    {
                        xtype: 'textfield',
                        height: '',
                        label: '微信号',
                        name: 'webchatName'
                    },
                    {
                        xtype: 'textfield',
                        label: '用户名',
                        name: 'username',
                        maxLength: 25
                    },
                    {
                        xtype: 'passwordfield',
                        label: '密码',
                        name: 'password',
                        maxLength: 25
                    },
                    {
                        xtype: 'passwordfield',
                        label: '确认密码',
                        name: 'confirmPass',
                        maxLength: 25
                    },
                    {
                        xtype: 'selectfield',
                        label: '性别',
                        name: 'gender',
                        options: [
                            {
                                text: '男',
                                value: '0'
                            },
                            {
                                text: '女',
                                value: '1'
                            }
                        ]
                    },
                    {
                        xtype: 'spinnerfield',
                        label: '年龄',
                        name: 'age',
                        maxValue: 100,
                        minValue: 1,
                        stepValue: 1,
                        defaultValue: 25
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'provinceSelect',
                        label: '省份',
                        name: 'province',
                        displayField: 'name',
                        store: 'ProvinceStore',
                        valueField: 'id'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'citySelect',
                        label: '城市',
                        name: 'city',
                        displayField: 'name',
                        store: 'CityStore',
                        valueField: 'id',
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    Ext.getStore('CityStore').filter('provinceId', 1);
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        label: '职业属性',
                        name: 'position',
                        options: [
                            {
                                text: '销售',
                                value: '1'
                            },
                            {
                                text: '技术',
                                value: '2'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'registerButton',
                margin: 20,
                padding: 8,
                ui: 'confirm-round',
                text: '注册'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        docked: 'left',
                        itemId: 'backBtn',
                        ui: 'back',
                        text: '返回'
                    },
                    {
                        xtype: 'label',
                        centered: true,
                        html: '注册'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onProvinceChange',
                event: 'change',
                delegate: '#provinceSelect'
            }
        ]
    },

    onProvinceChange: function(selectfield, newValue, oldValue, eOpts) {
        Ext.getStore('CityStore').filter('provinceId', newValue);
    }

});