/*
 * File: app/view/TaskList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.TaskList', {
    extend: 'Ext.Panel',
    alias: 'widget.tasklist',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.plugin.PullRefresh',
        'Ext.DateExtras'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                baseCls: 'x-toolbar toolbar-title',
                docked: 'top',
                title: '任务大厅',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'back',
                        ui: 'plain',
                        icon: 'true',
                        iconAlign: 'center',
                        iconCls: 'arrow_left'
                    }
                ]
            },
            {
                xtype: 'list',
                itemTpl: [
                    '{title}'
                ],
                store: 'taskStore',
                plugins: [
                    {
                        lastUpdatedDateFormat: 'Y-m-d H:i',
                        lastUpdatedText: '上次刷新时间',
                        loadedText: '加载完成',
                        loadingText: '正在加载',
                        pullText: '下拉可以更新',
                        releaseText: '松开开始更新',
                        type: 'pullrefresh'
                    }
                ]
            }
        ]
    }

});