/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Ext.MessageBox'
    ],
    models: [
        'Task',
        'User'
    ],
    stores: [
        'TaskStore',
        'ProvinceStore',
        'CityStore'
    ],
    views: [
        'LoginForm',
        'MainPanel',
        'TaskList',
        'RegisterForm',
        'PullRefreshPlugin'
    ],
    controllers: [
        'UserController',
        'MainController'
    ],
    isIconPrecomposed: true,
    name: 'app',

    launch: function() {
        var dataStore = Ext.create('Ext.data.Store', {
            model : "app.model.User"
        });
        dataStore.load();
        var index = dataStore.find('id', "1");
        var user = dataStore.getAt(index);
        if (user) {
            Ext.create('app.view.MainPanel', {fullscreen: true});
        } else {
            Ext.create('app.view.LoginForm', {fullscreen: true});
        }
    }

});
