/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.controller.MainController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainPanel: 'mainpanel',
            taskList: 'tasklist'
        },

        control: {
            "mainpanel #taskList": {
                tap: 'toTaskList'
            },
            "tasklist #back": {
                tap: 'toMainPanel'
            },
            "mainpanel #logout": {
                tap: 'logout'
            }
        }
    },

    toTaskList: function(button, e, eOpts) {
        var taskList = Ext.createByAlias('widget.tasklist');
        var mainPanel = this.getMainPanel();
        mainPanel.destroy();
        taskList.show();
    },

    toMainPanel: function(button, e, eOpts) {
        var mainPanel = Ext.createByAlias('widget.mainpanel');
        var taskList = this.getTaskList();
        taskList.destroy();
        mainPanel.show();
    },

    logout: function(button, e, eOpts) {
        var dataStore = Ext.create('Ext.data.Store', {
            model : "app.model.User"
        });
        dataStore.load();
        var index = dataStore.find('id', "1");
        var user = dataStore.getAt(index);
        if (user) {
            user.erase();
        }
        var loginform = Ext.createByAlias('widget.loginform');
        var mainPanel = this.getMainPanel();
        mainPanel.destroy();
        loginform.show();
    }

});