/*
 * File: app/controller/UserController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.controller.UserController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            registerPanel: 'registerform',
            loginPanel: 'loginform',
            mainPanel: 'mainpanel'
        },

        control: {
            "loginform #registerBtn": {
                tap: 'showRegister'
            },
            "registerform #backBtn": {
                tap: 'backToLogin'
            },
            "loginform #loginButton": {
                tap: 'login'
            },
            "registerform #registerButton": {
                tap: 'register'
            }
        }
    },

    showRegister: function(button, e, eOpts) {

        var registerForm = Ext.createByAlias('widget.registerform');
        var loginForm = this.getLoginPanel();
        loginForm.hide();
        registerForm.show();

    },

    backToLogin: function(button, e, eOpts) {

        var registerForm = this.getRegisterPanel();
        var loginForm = this.getLoginPanel();
        loginForm.show();
        registerForm.hide();

    },

    login: function(button, e, eOpts) {
        var form = button.up('formpanel'),			// Login form
        	values = form.getValues(),				// Form values
        	loginPanel = this.getLoginPanel();

        if(values.j_username === '' || values.j_password === ''){
            Ext.Msg.alert("提示", '用户名和密码不能为空');
            return;
        }

        // 连接登录接口成功
        var successCallback = function(resp, ops) {
            var loginResult = resp.responseText;
            if(loginResult === 'success'){
                //保存用户信息,下次打开直接到达主页
                var store = Ext.create('app.model.User', {
                                username : values.j_username,
                                password : values.j_password,
                                id : "1"
                            });
                store.save();

                var mainPanel = Ext.createByAlias('widget.mainpanel');
                loginPanel.hide();
                mainPanel.show();

            } else {
                Ext.Msg.alert("登录失败", '用户名或密码不正确');
            }

        };

        // 网络错误
        var failureCallback = function(resp, ops) {

            Ext.Msg.alert("提示", '网络连接失败');

        };


        // 登录请求
        Ext.Ajax.request({
            url: "http://192.168.2.101:8080/weixin/sencha/j_spring_security_check",
        		params: values,
        		success: successCallback,
        		failure: failureCallback
        });


    },

    register: function(button, e, eOpts) {
        var form = button.up('formpanel'),			// Login form
            values = form.getValues(),				// Form values
            loginPanel = this.getLoginPanel(),
            registerForm = this.getRegisterPanel();

        if(values.webchatName === '') {
            Ext.Msg.alert("提示", '微信号不能为空');
            return;
        } else if(values.username === '') {
            Ext.Msg.alert("提示", '用户名不能为空');
            return;
        } else if(values.password === '') {
            Ext.Msg.alert("提示", '密码不能为空');
            return;
        } else if(values.confirmPass === '') {
            Ext.Msg.alert("提示", '确认密码不能为空');
            return;
        } else if(values.password !== values.confirmPass) {
            Ext.Msg.alert("提示", '密码不一致');
            return;
        }

        // 连接注册接口成功
        var successCallback = function(resp, ops) {

            var registerResult = resp.responseText;
            if(registerResult === 'success') {
                Ext.Msg.alert("提示", '注册成功');

                registerForm.hide();
                loginPanel.show();
            } else {
                Ext.Msg.alert("提示", '注册失败');
            }


        };

        // 网络错误
        var failureCallback = function(resp, ops) {

            Ext.Msg.alert("提示", '网络连接失败');

        };

        // 注册请求
        Ext.Ajax.request({
        		url: "/weixin/sencha/register.htm",
        		params: values,
        		success: successCallback,
        		failure: failureCallback
        });

    }

});